### ISSUE TITLE
enrichment analysis for repeat elements intersected with SV

### ISSUE THREAD

**Issue by lx-1011** [quanc1989/SV-ONT-Tibetan#2]
Dear @quanc1989 
Thanks your share about this useful and detailed analyses pipeline. I have a question about Log2 foldchange (LFC) of enrichment analysis for repeat elements intersected with breakpoint junction sequence in your article, Result 2. How did you calculate the LFC ? In fact, I also run repeatmasker to get TE lib, and obtained the TE intersected with SV. I am in trouble in enrichment analyses.
![image](https://user-images.githubusercontent.com/47030888/141652143-e4fb134a-4b3f-4ba6-a58a-00691c926982.png)

Thanks and wish you all the best
Li Xin

**Comment by quanc1989** [comment]
Dear @lx-1011 
The enrichment analysis is based on simulations.

Firstly, as you have already done, I calculated proportions of each repeat elements for the whole SV callsets.
Secondly, I run 1000 simulations and generated the same number of random genomic regions across the whole genome, each of them have the same length as my real SVs. 
Thirdly, do the same calculations in the first step for each of the simulation callsets.
At last, you could calculate an LFC and also an experience p-value based on the real proportions of a specific repeat element in the real callset compared to the 1000 simulation values.

You could see further detail information in the supplements of the manuscript. (https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02382-3)

Hope I anwsered your question.

Quan Cheng

**Comment by lx-1011** [comment]
Hi @quanc1989 ,
thank you for the reply. I have totally understand your answer and run it sussessfuly.
Thank you!
Cheers,
Li Xin
